package com.leon.model;

public enum RequestTypeEnum
{
    CASH_CHECK_REQUEST,
    POSITION_CHECK_REQUEST,
    EXECUTION_MESSAGE,
    LONG_AND_COVERED_SHORT_SELL,
    LONG_SELL_ONLY,
    NAKED_SHORT_SELL,
    QUANTITY_AMEND_UP,
    QUANTITY_AMEND_DOWN,
    NONE
}
